group=club.selbsthilfe.kuscheltiermafia
version=1.0-SNAPSHOT
description=The plugin that manages basic lobby logics but also the cosmetics aroud the while selbstihlfe.club network, lobby hunts and ralleys and in the future the EchoCraft trading game with certifed gambling.
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
