entity-tags:  #Tags of the entities that mark places
  spawn: "spawn_point"  #Where a player gets teleported upon joining the Lobby

#Don't fill this in for code in VCS
database:
  host:
  port:
  database:
  username:
  password: